#!/bin/bash
rsync -av ~/Data/                                   /Volumes/HAYSAFE3/Data
rsync -av ~/Desktop/                                /Volumes/HAYSAFE3/Data/Desktop
rsync -av ~/dev/                                    /Volumes/HAYSAFE3/Data/dev
rsync -av ~/.ssh/                                   /Volumes/HAYSAFE3/Data/ssh
rsync -av ~/Documents/                              /Volumes/HAYSAFE3/Documents
rsync -av ~/Downloads/                              /Volumes/HAYSAFE3/Software_OSX
rsync -av ~/htdocs/                                 /Volumes/HAYSAFE3/Data/htdocs
rsync -av ~/Library/Mail/                           /Volumes/HAYSAFE3/Data/Email_cur_mailapp
rsync -av ~/Movies/Speelfilms/                      /Volumes/HAYSAFE3/Media/Speelfilms
rsync -av ~/Movies/Video/                           /Volumes/HAYSAFE3/Media/Video
rsync -av ~/Music/MP3/                              /Volumes/HAYSAFE3/Media
rsync -av ~/Pictures/                               /Volumes/HAYSAFE3/Media/Afbeeldingen
rsync -av ~/Projecten/ --exclude Muziek/            /Volumes/HAYSAFE3/Projecten
rsync -av ~/Projecten/Muziek/                       /Volumes/HAYSAFE3/Muziek/
rsync -av ~/svn/                                    /Volumes/HAYSAFE3/Data/svn
rsync -av "/Users/hay/Music/iTunes/iTunes Music/Podcasts/"   /Volumes/HAYSAFE3/Media/Podcasts
# forget it, this takes fucking ages
# rsync -av ~/ParallelsVM/                            /Volumes/HAYSAFE3/Data/ParallelsVM
growlnotify -m "Backup complete!"