#!/bin/bash
rsync -av ~/Library/Mail/                           /Volumes/HAYSAFE2/Data/Email_cur_mailapp
rsync -av ~/.ssh/                                   /Volumes/HAYSAFE2/Data/ssh
rsync -av ~/Documents/                              /Volumes/HAYSAFE2/Documents
rsync -av ~/htdocs/ --exclude checkouts/            /Volumes/HAYSAFE2/Data/htdocs
rsync -av ~/Pictures/                               /Volumes/HAYSAFE2/Media/Afbeeldingen
rsync -av ~/Projecten/Muziek/                       /Volumes/HAYSAFE2/Muziek/
rsync -av ~/Data/                                   /Volumes/HAYSAFE2/Data
rsync -av ~/Desktop/                                /Volumes/HAYSAFE2/Data/Desktop
rsync -av ~/dev/ --exclude checkouts/               /Volumes/HAYSAFE2/Data/dev
rsync -av /Applications/MAMP/                       /Volumes/HAYSAFE2/Data/MAMP
rsync -av ~/Movies/Video/                           /Volumes/HAYSAFE2/Media/Video
rsync -av ~/Projecten/ --exclude Muziek/            /Volumes/HAYSAFE2/Projecten
rsync -av ~/svn/                                    /Volumes/HAYSAFE2/Data/svn
rsync -av ~/Music/MP3/                              /Volumes/HAYSAFE2/Media
rsync -av ~/Downloads/ --exclude Incoming/ --exclude Paketten/          /Volumes/HAYSAFE2/Software_OSX
growlnotify -m "Backup complete!"