#!/bin/bash
svn up ~/htdocs/magnolia/
svn up ~/htdocs/frontend/
svn up ~/htdocs/wpmu
svn up ~/htdocs/wordpress-mu/wp-content/plugins/
svn up ~/htdocs/wordpress-mu/wp-content/themes/
svn up ~/htdocs/wordpress-mu/wp-content/mu-plugins/

cd ~/htdocs/js/
git svn fetch